import type { Metadata } from 'next';
import { MyAppContextProvider } from './context/myContext'
import './globals.css'
import Footer from './components/footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MyAppContextProvider>
          {children}
        </MyAppContextProvider>
        <Footer />
      </body>
    </html>
  )
}
